const express=require('express');
const session=require('express-session');
const bcrypt=require('bcryptjs');
const Database=require('better-sqlite3');
const methodOverride=require('method-override');
const helmet=require('helmet');
const rateLimit=require('express-rate-limit');
const path=require('path');
const fs=require('fs');

const app=express();app.set('trust proxy', 1);
const dataDir=path.join(__dirname,'data'); if(!fs.existsSync(dataDir)) fs.mkdirSync(dataDir,{recursive:true});
const db=new Database(path.join(dataDir,'board.db')); db.pragma('journal_mode=WAL'); db.pragma('foreign_keys=ON');

db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT NOT NULL UNIQUE,password TEXT NOT NULL,display_name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',avatar TEXT, reputation INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,slug TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS questions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,category_id INTEGER NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,image_url TEXT,views INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(category_id) REFERENCES categories(id));
CREATE TABLE IF NOT EXISTS answers(id INTEGER PRIMARY KEY AUTOINCREMENT,question_id INTEGER NOT NULL,user_id INTEGER NOT NULL,body TEXT NOT NULL,image_url TEXT,is_accepted INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS votes(id INTEGER PRIMARY KEY AUTOINCREMENT,answer_id INTEGER NOT NULL,user_id INTEGER NOT NULL,value INTEGER NOT NULL CHECK(value IN(1,-1)),UNIQUE(answer_id,user_id),FOREIGN KEY(answer_id) REFERENCES answers(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS bookmarks(id INTEGER PRIMARY KEY AUTOINCREMENT,question_id INTEGER NOT NULL,user_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(question_id,user_id),FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,message TEXT NOT NULL,url TEXT,read INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS tags(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS question_tags(question_id INTEGER NOT NULL,tag_id INTEGER NOT NULL,PRIMARY KEY(question_id,tag_id),FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE,FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE);
`);
const cats=[['เทคโนโลยี','technology'],['การเขียนโปรแกรม','programming'],['ไอทีและคอมพิวเตอร์','it'],['การศึกษา','education'],['งานและอาชีพ','career'],['ธุรกิจ','business'],['เกม','games'],['ทั่วไป','general']]; const insCat=db.prepare('INSERT OR IGNORE INTO categories(name,slug) VALUES(?,?)'); cats.forEach(c=>insCat.run(...c));
if(!db.prepare('SELECT id FROM users LIMIT 1').get()) db.prepare('INSERT INTO users(username,password,display_name,role,reputation) VALUES(?,?,?,?,?)').run('admin',bcrypt.hashSync('admin1234',10),'ผู้ดูแลระบบ','admin',100);

app.set('view engine','ejs'); app.set('views',path.join(__dirname,'views'));
app.use(helmet({contentSecurityPolicy:false})); app.use(express.urlencoded({extended:true,limit:'1mb'})); app.use(express.json({limit:'1mb'})); app.use(methodOverride('_method')); app.use(express.static(path.join(__dirname,'public')));
app.use(session({secret:process.env.SESSION_SECRET||'CHANGE_ME_SECRET',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*7}}));
const authLimiter=rateLimit({windowMs:15*60*1000,max:30,standardHeaders:true,legacyHeaders:false});
app.locals.formatDate=s=>new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(s+'Z'));
app.locals.initial=s=>String(s||'?').trim().charAt(0).toUpperCase();
app.use((req,res,next)=>{res.locals.user=req.session.user||null;res.locals.notifications=[];if(req.session.user) res.locals.notifications=db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 8').all(req.session.user.id);next();});
function requireAuth(req,res,next){if(!req.session.user)return res.redirect('/login?next='+encodeURIComponent(req.originalUrl));next()}
function adminOnly(req,res,next){if(!req.session.user||req.session.user.role!=='admin')return res.status(403).render('error',{message:'เฉพาะผู้ดูแลระบบเท่านั้น'});next()}
function notify(userId,message,url){if(userId&&userId!==undefined)db.prepare('INSERT INTO notifications(user_id,message,url) VALUES(?,?,?)').run(userId,message,url||'/');}
function tagsForQuestion(id){return db.prepare('SELECT t.* FROM tags t JOIN question_tags qt ON qt.tag_id=t.id WHERE qt.question_id=? ORDER BY t.name').all(id)}
function getQuestion(id,userId=0){return db.prepare(`SELECT q.*,u.display_name,u.avatar,c.name category_name,c.slug category_slug,(SELECT COUNT(*) FROM answers a WHERE a.question_id=q.id) answer_count,(SELECT COUNT(*) FROM bookmarks b WHERE b.question_id=q.id AND b.user_id=?) bookmarked FROM questions q JOIN users u ON u.id=q.user_id JOIN categories c ON c.id=q.category_id WHERE q.id=?`).get(userId,id)}

app.get('/',(req,res)=>{const q=String(req.query.q||'').trim(),cat=Number(req.query.category||0),tag=String(req.query.tag||'').trim();let where=[],p=[];if(q){where.push('(q.title LIKE ? OR q.body LIKE ?)');p.push('%'+q+'%','%'+q+'%')}if(cat){where.push('q.category_id=?');p.push(cat)}if(tag){where.push('EXISTS(SELECT 1 FROM question_tags qt JOIN tags t ON t.id=qt.tag_id WHERE qt.question_id=q.id AND t.name=?)');p.push(tag)}const sql=`SELECT q.*,u.display_name,u.avatar,c.name category_name,(SELECT COUNT(*) FROM answers a WHERE a.question_id=q.id) answer_count,(SELECT COALESCE(SUM(v.value),0) FROM votes v JOIN answers a ON a.id=v.answer_id WHERE a.question_id=q.id) score FROM questions q JOIN users u ON u.id=q.user_id JOIN categories c ON c.id=q.category_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY q.created_at DESC LIMIT 50`;const questions=db.prepare(sql).all(...p);const categories=db.prepare(`SELECT c.*,COUNT(q.id) count FROM categories c LEFT JOIN questions q ON q.category_id=c.id GROUP BY c.id ORDER BY c.name`).all();const popularTags=db.prepare('SELECT t.name,COUNT(qt.question_id) count FROM tags t JOIN question_tags qt ON qt.tag_id=t.id GROUP BY t.id ORDER BY count DESC,t.name LIMIT 12').all();const stats={questions:db.prepare('SELECT COUNT(*) n FROM questions').get().n,answers:db.prepare('SELECT COUNT(*) n FROM answers').get().n,users:db.prepare('SELECT COUNT(*) n FROM users').get().n};res.render('home',{questions,categories,stats,q,cat,tag,popularTags});});

app.get('/register',(req,res)=>res.render('register',{error:null}));
app.post('/register',authLimiter,(req,res)=>{const username=String(req.body.username||'').trim().toLowerCase(),password=String(req.body.password||''),display=String(req.body.display_name||'').trim();if(!/^[a-z0-9_]{3,24}$/.test(username)||password.length<6||display.length<2)return res.render('register',{error:'ชื่อผู้ใช้ใช้ a-z, 0-9, _ ความยาว 3-24 ตัว และรหัสผ่านอย่างน้อย 6 ตัวอักษร'});try{const info=db.prepare('INSERT INTO users(username,password,display_name) VALUES(?,?,?)').run(username,bcrypt.hashSync(password,10),display);req.session.user={id:info.lastInsertRowid,username,display_name:display,role:'user',reputation:0};res.redirect('/')}catch(e){res.render('register',{error:'ชื่อผู้ใช้นี้ถูกใช้แล้ว'})}});
app.get('/login',(req,res)=>res.render('login',{error:null}));
app.post('/login',authLimiter,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE username=?').get(String(req.body.username||'').trim().toLowerCase());if(!u||!bcrypt.compareSync(req.body.password||'',u.password))return res.render('login',{error:'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'});req.session.user={id:u.id,username:u.username,display_name:u.display_name,role:u.role,reputation:u.reputation};res.redirect(req.query.next||'/')});
app.post('/logout',(req,res)=>req.session.destroy(()=>res.redirect('/')));

app.get('/ask',requireAuth,(req,res)=>res.render('ask',{categories:db.prepare('SELECT * FROM categories ORDER BY name').all(),error:null}));
app.post('/ask',requireAuth,(req,res)=>{const title=String(req.body.title||'').trim(),body=String(req.body.body||'').trim(),category=Number(req.body.category_id),image=String(req.body.image_url||'').trim(),raw=String(req.body.tags||'');if(title.length<5||body.length<10||!category)return res.render('ask',{categories:db.prepare('SELECT * FROM categories ORDER BY name').all(),error:'หัวข้ออย่างน้อย 5 ตัวอักษร และเนื้อหาอย่างน้อย 10 ตัวอักษร'});const info=db.prepare('INSERT INTO questions(user_id,category_id,title,body,image_url) VALUES(?,?,?,?,?)').run(req.session.user.id,category,title,body,image);const qid=info.lastInsertRowid;raw.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean).slice(0,6).forEach(name=>{db.prepare('INSERT OR IGNORE INTO tags(name) VALUES(?)').run(name);const t=db.prepare('SELECT id FROM tags WHERE name=?').get(name);db.prepare('INSERT OR IGNORE INTO question_tags(question_id,tag_id) VALUES(?,?)').run(qid,t.id)});res.redirect('/question/'+qid)});

app.get('/question/:id',(req,res)=>{const id=Number(req.params.id);const q=getQuestion(id,req.session.user?.id||0);if(!q)return res.status(404).render('error',{message:'ไม่พบกระทู้นี้'});db.prepare('UPDATE questions SET views=views+1 WHERE id=?').run(id);q.views++;const answers=db.prepare(`SELECT a.*,u.display_name,u.avatar,COALESCE((SELECT SUM(value) FROM votes v WHERE v.answer_id=a.id),0) score,(SELECT value FROM votes v WHERE v.answer_id=a.id AND v.user_id=?) my_vote FROM answers a JOIN users u ON u.id=a.user_id WHERE a.question_id=? ORDER BY a.is_accepted DESC,score DESC,a.created_at ASC`).all(req.session.user?.id||0,id);res.render('question',{q,answers,tags:tagsForQuestion(id)});});
app.post('/question/:id/answer',requireAuth,(req,res)=>{const id=Number(req.params.id),body=String(req.body.body||'').trim(),image=String(req.body.image_url||'').trim(),q=db.prepare('SELECT * FROM questions WHERE id=?').get(id);if(!q||!body)return res.redirect('/question/'+id+'#answer-form');const a=db.prepare('INSERT INTO answers(question_id,user_id,body,image_url) VALUES(?,?,?,?)').run(id,req.session.user.id,body,image);if(q.user_id!==req.session.user.id)notify(q.user_id,`${req.session.user.display_name} ตอบคำถามของคุณ`, `/question/${id}#answer-${a.lastInsertRowid}`);res.redirect('/question/'+id+'#answers')});
app.post('/answer/:id/vote',requireAuth,(req,res)=>{const a=db.prepare('SELECT * FROM answers WHERE id=?').get(Number(req.params.id));if(!a)return res.redirect('/');const value=Number(req.body.value)===-1?-1:1,old=db.prepare('SELECT * FROM votes WHERE answer_id=? AND user_id=?').get(a.id,req.session.user.id);let delta=0;if(old&&old.value===value){db.prepare('DELETE FROM votes WHERE id=?').run(old.id);delta=-old.value}else if(old){db.prepare('UPDATE votes SET value=? WHERE id=?').run(value,old.id);delta=value-old.value}else{db.prepare('INSERT INTO votes(answer_id,user_id,value) VALUES(?,?,?)').run(a.id,req.session.user.id,value);delta=value}db.prepare('UPDATE users SET reputation=reputation+? WHERE id=?').run(delta,a.user_id);if(a.user_id!==req.session.user.id&&value===1)notify(a.user_id,`${req.session.user.display_name} โหวตคำตอบของคุณ`,`/question/${a.question_id}#answer-${a.id}`);res.redirect('/question/'+a.question_id+'#answer-'+a.id)});
app.post('/answer/:id/accept',requireAuth,(req,res)=>{const a=db.prepare('SELECT a.*,q.user_id q_user FROM answers a JOIN questions q ON q.id=a.question_id WHERE a.id=?').get(Number(req.params.id));if(a&&a.q_user===req.session.user.id&&!a.is_accepted){db.prepare('UPDATE answers SET is_accepted=0 WHERE question_id=?').run(a.question_id);db.prepare('UPDATE answers SET is_accepted=1 WHERE id=?').run(a.id);db.prepare('UPDATE users SET reputation=reputation+15 WHERE id=?').run(a.user_id);if(a.user_id!==req.session.user.id)notify(a.user_id,'คำตอบของคุณได้รับการยอมรับแล้ว',`/question/${a.question_id}#answer-${a.id}`)}res.redirect('/question/'+(a?a.question_id:0)+'#answer-'+(a?a.id:''))});
app.post('/question/:id/bookmark',requireAuth,(req,res)=>{const id=Number(req.params.id),old=db.prepare('SELECT id FROM bookmarks WHERE question_id=? AND user_id=?').get(id,req.session.user.id);if(old)db.prepare('DELETE FROM bookmarks WHERE id=?').run(old.id);else db.prepare('INSERT INTO bookmarks(question_id,user_id) VALUES(?,?)').run(id,req.session.user.id);res.redirect('/question/'+id)});
app.post('/notifications/read-all',requireAuth,(req,res)=>{db.prepare('UPDATE notifications SET read=1 WHERE user_id=?').run(req.session.user.id);res.redirect(req.get('Referer')||'/')});
app.get('/bookmarks',requireAuth,(req,res)=>{const questions=db.prepare(`SELECT q.*,u.display_name,c.name category_name,(SELECT COUNT(*) FROM answers a WHERE a.question_id=q.id) answer_count FROM bookmarks b JOIN questions q ON q.id=b.question_id JOIN users u ON u.id=q.user_id JOIN categories c ON c.id=q.category_id WHERE b.user_id=? ORDER BY b.created_at DESC`).all(req.session.user.id);res.render('bookmarks',{questions})});

app.get('/profile/:id',(req,res)=>{const id=Number(req.params.id),u=db.prepare('SELECT id,username,display_name,role,avatar,reputation,created_at FROM users WHERE id=?').get(id);if(!u)return res.status(404).render('error',{message:'ไม่พบผู้ใช้งาน'});const questions=db.prepare(`SELECT q.*,c.name category_name,(SELECT COUNT(*) FROM answers a WHERE a.question_id=q.id) answer_count FROM questions q JOIN categories c ON c.id=q.category_id WHERE q.user_id=? ORDER BY q.created_at DESC`).all(id);const answerCount=db.prepare('SELECT COUNT(*) n FROM answers WHERE user_id=?').get(id).n;res.render('profile',{u,questions,answerCount})});
app.get('/settings',requireAuth,(req,res)=>{const u=db.prepare('SELECT id,username,display_name,avatar FROM users WHERE id=?').get(req.session.user.id);res.render('settings',{u,error:null,ok:null})});
app.post('/settings',requireAuth,(req,res)=>{const display=String(req.body.display_name||'').trim(),avatar=String(req.body.avatar||'').trim();if(display.length<2)return res.render('settings',{u:{...req.session.user,display_name:display,avatar},error:'ชื่อแสดงผลสั้นเกินไป',ok:null});db.prepare('UPDATE users SET display_name=?,avatar=? WHERE id=?').run(display,avatar,req.session.user.id);req.session.user.display_name=display;res.render('settings',{u:{...req.session.user,display_name:display,avatar},error:null,ok:'บันทึกข้อมูลแล้ว'})});

app.get('/admin',requireAuth,adminOnly,(req,res)=>{const users=db.prepare('SELECT id,username,display_name,role,reputation,created_at FROM users ORDER BY id DESC').all();const questions=db.prepare(`SELECT q.id,q.title,q.created_at,u.display_name,c.name category_name,q.views,(SELECT COUNT(*) FROM answers a WHERE a.question_id=q.id) answers FROM questions q JOIN users u ON u.id=q.user_id JOIN categories c ON c.id=q.category_id ORDER BY q.id DESC LIMIT 100`).all();const stats={users:db.prepare('SELECT COUNT(*) n FROM users').get().n,questions:db.prepare('SELECT COUNT(*) n FROM questions').get().n,answers:db.prepare('SELECT COUNT(*) n FROM answers').get().n,bookmarks:db.prepare('SELECT COUNT(*) n FROM bookmarks').get().n};res.render('admin',{users,questions,stats})});
app.post('/admin/delete-question/:id',requireAuth,adminOnly,(req,res)=>{const id=Number(req.params.id);db.prepare('DELETE FROM questions WHERE id=?').run(id);res.redirect('/admin')});
app.post('/admin/delete-user/:id',requireAuth,adminOnly,(req,res)=>{const id=Number(req.params.id);if(id!==req.session.user.id)db.prepare('DELETE FROM users WHERE id=?').run(id);res.redirect('/admin')});

app.use((req,res)=>res.status(404).render('error',{message:'ไม่พบหน้าที่ต้องการ'}));
const port=process.env.PORT||3000;app.listen(port,()=>console.log(`Knowledge Board v2 running at http://localhost:${port}`));
